### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by a-tarr** [a-tarr/Fleetr#1]
Quick roadmap of features that I intend to work on:

**Core**
- [x] Make app mobile friendly
- [ ] Optimise algorithm and properly evaluate to maximum capacity of point value (instead of brute forcing as I am now)

**Features**
- [ ] Add ability to add keyword filtering
- [ ] Add ability to add defense token filtering
- [ ] Add ability to have dice filtering
- [ ] Add ability to have a more granular ratio. For example,  user selects 500 total points, and states that 150 must be squadrons.
- [ ] Randomise upgrade cards.

Upgrade cards: Should it be pick 100 points of upgrade cards than split across per ship? Or make it completely random?
